version: '3.9'
services:
  enConfigurationInterface:
    image: en-configuration-interface:1.0
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9898:9898"
    env_file: variablesList.env
    
    